//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////Fichier javascript permettant à la création du tableau/////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//////////////////////////////Initialisation variable k correspondant à notre nombre de ligne necessaire//////////////////////////////////////
var k=85;
//////////////////////////////////////////////////////Initialisation variables titre////////////////////////////////////////////////////////
var titre1, titre2;
//////////////Initialisation des variables ligne (correspondant chacune à une colonne) en utilisant notre indice k/////////////////////////
var Ligne1 = new Array(k), Ligne2 = new Array(k), Ligne3 = new Array(k), Ligne4 = new Array(k), Ligne5 = new Array(k), Ligne6 = new Array(k),
 Ligne7 = new Array(k), Ligne8 = new Array(k), Ligne9 = new Array(k), Ligne0 = new Array(k);
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////Variable début du tableau et affichant le nom des colonnes///////////////////////////////////////////////
titre1 = "<table><tr><th>Numéro de ligne</th><th>Axe</th><th>DE</th><th>A</th><th>Sens 1</th><th>(DE vers à)</th><th>Sens 2</th><th>(à vers de)</th><th>Secteur PIARA</th><th>Département(s)</th></tr>";
/////////////////////////////////////Variable affichant le sous-nom des colones///////////////////////////////////////////////
titre2 = "<tr><th></th><th></th><th>(petite maille</th><th>(petite maille)</th><th>PL</th><th>TV</th><th>PL</th><th>TV</th><th></th><th></th></tr>";
//////////////////////////////////////////////////////Numéro des tronçons///////////////////////////////////////////////
Ligne1 = ["1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30","31","32","33","34","35","36","37","38","39","40","41","42","43","44","45","46","47","48","49","50","51","52","53","54","55","56","57","58","59","60","61","62","63","64","65","66","67","68","69","70","71","72","73","74","75","76","77","78","79","80","81","82","83","84","85"];
//////////////////////////////////////////////////////Nom des routes///////////////////////////////////////////////
Ligne2 = ["A39","A40","A40","A40","A40","A406","A404","N205","A40","A40","N201","A41N","A41N","A410","A43O","A43O","A43O","A43E","A43E","A43E","A48","A48","A480","N87","A41S","A49","N532","A7S","A7S","A6","A6 M6","M6 M7","A7N","A7N","A7N","A7N","A42","A42","A42","A43O","A43O","A43O","A46N","A466","A46N","A46S","A47","A432N","A432S","A450","N346","BPNL","D301","D383","D383","A47","A47","N88","N88","N88","A72","A72","N7","N82","A89","A89","A89","A89","A89","A71","A71","A71","A71","A71","A89 Ouest","A75","A75","A75","A75","A714","N145","N7","N7","N79","N79"];
//////////////////////////////////////////////////////Colonne DE///////////////////////////////////////////////
Ligne3 = ["Limite département du Jura (Zone Est)","Jonction A40/A41N","Barrière de péage de Viry","Jonction A40/A42","Jonction A39/A40","Jonction A406/A40","Jonction A404/A40","Limite Italie","Jonction A40/N205","Jonction A40/A410","Jonction N201/A43/A41N","Jonction A41N/A43/N201","Jonction A41N/A410","Jonction A40/A410","Barrière de péage de Saint Quentin-Fallavier","Nœud A48/A43 Coiranne","Limite département de la Savoie","Jonction A43/N201","Jonction A43/A41S","Jonction A43/A430","Nœud A48/A49 Coiranne","Nœud A48/A49 Voreppe","Jonction A48/A480","Jonction N87/A480","Jonction A41S/N87","Jonction A49/A48","Jonction N532/N7","Barrière de péage de Vienne-Reventin","Échangeur n° 15 Valence Sud","Limite département de Saône-et-Loire","Noeud Anse A6/A46N","Noeud TEO","Nœud A450","St Fons","BUS","Nœud Ternay A7/A46S/A47","Jonction A42/D383","Jonction A42/N346 Nœud des Iles","Jonction A42/A432","Jonction A43/D383","Jonction N346/A43","Jonction A432/A43","Jonction A6/A46N","Jonction A466/A6","Jonction A432/A46N Les Echets","Jonction N346/A46S","Jonction A47/A7","Jonction A432/A46N Les Echets","Jonction A432/A42","Jonction A450/A7N","Jonction N346/A46N","Jonction BPNL/A6","Jonction D301/A7N","Jonction D383/A42","nœud D383/A43","Limite département Rhône / Loire","Echangeur de la Madeleine","Jonction N88/A47","Jonction N88/A72","Limite département Loire /  Haute-Loire","Jonction A72/N88","Jonction A89/A72","Limite département Loire / Allier","Jonction N82/N7","Jonction A89/A72","Jonction A89/N82","Limite département Rhône / Loire","Jonction A89/A710","Limite département Loire / Puy-De-Dôme","Limite département du Cher (Zone Ouest)","Jonction A71/A714","Jonction A71/N79","Limite département Puy-de-Dôme / Allier","Jonction A71/A89","Limite département de la Corrèze (Zone Sud-Ouest)","Jonction A71/A75","Limite département Puy-de-Dôme / Haute-Loire","Jonction A75/N102","Limite département Cantal / Haute-Loire","Jonction A714/A71","Limite département de la Creuse (Zone Sud-Ouest)","Limite département de la Nièvre (Zone Est)","Jonction N79/N7 Moulins","Jonction N79/A71","Jonction N79/N7 Moulins"];
//////////////////////////////////////////////////////Colonne A///////////////////////////////////////////////
Ligne4 = ["Jonction A39/A40","Barrière de péage de Viry","Jonction A40/A42","Jonction A39/A40","Limite département Saône-et-Loire (Zone Est)","Limite département Saône-et-Loire (Zone Est)","Jonction A404/D31","Jonction N205/A40","Jonction A40/A410","Jonction A40/A41N","Jonction A43/N201","Jonction A41N/A410","Jonction A40/A41N","Jonction A41N/A410","Nœud A48/A43 Coiranne","Limite département de la Savoie","Jonction A43/N201/A41N","Jonction A43/A41S","Jonction A43/A430","Limite Italie","Nœud A48/A49 Voreppe","Jonction A48/A480","Jonction A480/N85","Jonction N87/A41S","Jonction A41S/A43","Jonction A49/N532","Jonction A49/N532","Échangeur n° 15 Valence Sud","Limite département de Vaucluse (Zone Sud)","Noeud Anse A6/A46N","Noeud TEO","Nœud A450","St Fons","BUS","Nœud Ternay A7/A46S/A47","Barrière de péage de Vienne-Reventin","Jonction A42/N346 Nœud des Iles","Jonction A42/A432","Jonction A42/A40","Jonction N346/A43","Jonction A432/A43","Barrière de péage de Saint Quentin-Fallavier","Jonction A432/A46N Les Echets","Jonction A466/A46N","Jonction N346/A46N","Jonction A7/A46S","Limite département Rhône / Loire","Jonction A432/A42","Jonction A432/A43","Jonction A450/D342","Jonction N346/A46S","Jonction BPNL/A42","Jonction D301/N346","nœud D383/A43","Jonction D383/A7N","Echangeur de la Madeleine","Jonction A47/N88","Jonction N88/A72","Limite département Loire /  Haute-Loire","Monistrol-sur-Loire","Barrière de péage de Veauchette","Barrière de péage de Veauchette","Jonction N82/N7","Jonction N82/A89","Jonction A89/N82","Limite département Rhône / Loire","Jonction A89/A6","Limite département Loire / Puy-De-Dôme","Jonction A89/A72","Jonction A71/A714","Jonction A71/N79","Limite département Puy-de-Dôme / Allier","Jonction A71/A89","Jonction A71/A75","Jonction A89/A71","Limite département Puy-de-Dôme / Haute-Loire","Jonction A75/N102","Limite département Cantal / Haute-Loire","Limite département de la Lozère (Zone Sud)","Jonction A714/N145","Jonction N145/A714","Jonction N79/N7 Moulins","Limite département Loire / Allier","Jonction N79/N7 Moulins","Limite département de la Saône-et-Loire (Zone Est)"];
//////////////////////////////////////////////////////Sens 1 PL Initialisé vide///////////////////////////////////////////////
Ligne5 = ["","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","",""];
//////////////////////////////////////////////////////Sens 1 TV Initialisé vide///////////////////////////////////////////////
Ligne6 = ["","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","",""];
//////////////////////////////////////////////////////Sens 2 PL Initialisé vide///////////////////////////////////////////////
Ligne7 = ["","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","",""];
//////////////////////////////////////////////////////Sens 2 TV Initialisé vide///////////////////////////////////////////////
Ligne8 = ["","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","",""];
//////////////////////////////////////////////////////Secteur Piarra///////////////////////////////////////////////
Ligne9 = ["A40 Mâcon Genève (1)","A40 Mâcon Genève (1)","A40 Mâcon Genève (1)","A40 Mâcon Genève (1)","A40 Mâcon Genève (1)","A40 Mâcon Genève (1)","A40 Mâcon Genève (1)","A40 Mâcon Genève (1)","A40 Genève Italie (2)","A40 Genève Italie (2)","A40 Genève Italie (2)","A41 Chambéry Genève (3)","A41 Chambéry Genève (3)","A41 Chambéry Genève (3)","A41 Chambéry Genève (3)","A43 Lyon Chambéry (4)","A43 Lyon Chambéry (4)","A43 Chambéry Italie (5)","A43 Chambéry Italie (5)","A43 Chambéry Italie (5)","A48 A49 A41S Grenoble (6)","A48 A49 A41S Grenoble (6)","A48 A49 A41S Grenoble (6)","A48 A49 A41S Grenoble (6)","A48 A49 A41S Grenoble (6)","A48 A49 A41S Grenoble (6)","A48 A49 A41S Grenoble (6)","Vienne Valence (7)","Valence Orange (8)","Belleville Vienne (9)","Belleville Vienne (9)","Belleville Vienne (9)","Belleville Vienne (9)","Belleville Vienne (9)","Belleville Vienne (9)","Belleville Vienne (9)","Belleville Vienne (9)","Belleville Vienne (9)","A40 Mâcon Genève (1)","Belleville Vienne (9)","Belleville Vienne (9)","Belleville Vienne (9)","Belleville Vienne (9)","Belleville Vienne (9)","Belleville Vienne (9)","Belleville Vienne (9)","Belleville Vienne (9)","Belleville Vienne (9)","Belleville Vienne (9)","Belleville Vienne (9)","Belleville Vienne (9)","Belleville Vienne (9)","Belleville Vienne (9)","Belleville Vienne (9)","Belleville Vienne (9)","A47 A72 N88 Saint-Étienne (10)","A47 A72 N88 Saint-Étienne (10)","A47 A72 N88 Saint-Étienne (10)","A47 A72 N88 Saint-Étienne (10)","A47 A72 N88 Saint-Étienne (10)","A47 A72 N88 Saint-Étienne (10)","A47 A72 N88 Saint-Étienne (10)","N7 A89 Roanne Balbigny Lyon (11)","N7 A89 Roanne Balbigny Lyon (11)","N7 A89 Roanne Balbigny Lyon (11)","N7 A89 Roanne Balbigny Lyon (11)","N7 A89 Roanne Balbigny Lyon (11)","CAA A89 Est (12)","CAA A89 Est (12)","CAA A71 (13)","CAA A71 (13)","CAA A71 (13)","CAA A71 (13)","CAA A71 (13)","CAA A89 Ouest (14)","CAA A75 (15)","CAA A75 (15)","CAA A75 (15)","CAA A75 (15)","RCEA N7 Moulins (16)","RCEA N7 Moulins (16)","RCEA N7 Moulins (16)","RCEA N7 Moulins (16)","RCEA N7 Moulins (16)","RCEA N7 Moulins (16)"];
//////////////////////////////////////////////////////Nom département///////////////////////////////////////////////
Ligne0 = ["Ain","Haute-Savoie","Ain + Haute-Savoie","Ain","Ain","Ain","Ain","Haute-Savoie","Haute-Savoie","Haute-Savoie","Savoie","Savoie + Haute-Savoie","Haute-Savoie","Haute-Savoie","Isère","Isère","Savoie","Savoie","Savoie","Savoie","Isère","Isère","Isère","Isère","Isère + Savoie","Drôme + Isère","Drôme","Isère + Drôme","Drôme" ,"Rhône","Rhône","Rhône","Rhône","Rhône","Rhône","Rhône + Isère","Rhône + Ain","Rhône + Isère","Rhône + Isère","Isère + Rhône","Isère + Rhône","Isère + Rhône","Rhône + Isère","Rhône","Rhône + Isère","Rhône","Rhône","Ain","Ain + Rhône + Isère","Rhône","Rhône","Rhône","Rhône","Rhône","Rhône","Loire","Loire","Loire","Loire","Haute-Loire","Loire","Loire","Loire","Loire","Loire","Loire","Rhône","Puy-de-Dôme","Loire","Allier","Allier","Allier","Puy-de-Dôme","Puy-de-Dôme","Puy-de-Dôme","Puy-de-Dôme","Haute-Loire","Haute-Loire","Cantal","Allier","Allier","Allier","Allier","Allier","Allier"];
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////Initialisation de notre variable text avec les deux titres/////////////////////////////////////
var text = titre1 += titre2;
//////////////////////////////////////////Fonction pour créer le tableau///////////////////////////////////////////////////
function CreationTableau(text) {
///////////////////////////////Boucle se lançant avec le nombre de nos tronçons (k)//////////////////////////////////////////////////////////
for (var i = 0; i < k; i++) {
////////////////////Ajout dans la variable text des balises de tableau et les valeurs de chacune des colonnes////////////////////////////////
  text += "<tr><th>" + Ligne1[i] + "</th>" + "<th>" + Ligne2[i] + "</th>"+ "<th>" + Ligne3[i] + "</th>"+ "<th>" + Ligne4[i] + "</th>" + 
  "<th>" + Ligne5[i] + "</th>" + "<th>" + Ligne6[i] + "</th>" + "<th>" + Ligne7[i] + "</th>" + "<th>" + Ligne8[i] + "</th>" + 
  "<th>" + Ligne9[i] + "</th>" + "<th>" + Ligne0[i] + "</th></tr>";
}
//////////////////////////////////////////Fermeture du tableau en ajoutant la balise table//////////////////////////////////////////////////
text += "</table>";
///////////////Affichage du tableau dans la balise <p> avec comme id Tableau dans projet_apz_v2.html////////////////////////////////////////
document.getElementById("Tableau").innerHTML = text;
}
//////////////////////////////////////////Lancement de la fonction///////////////////////////////////////////////////
CreationTableau(text);
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////